### PR TITLE
AFDP-1871, AFDP-647: Dashboard widget title restriction & change Dashboard layout editor

### PR DESCRIPTION
**Pull request by AngjelSpasovski**
For the purpose of task ``AFDP-1871: Dashboard Title restriction`` in this pull request I change the ``angular-dashboard-framework-tpls.js`` file I create ``$scope.maxLength = 20;`` to restrict the insert maximum length on ``widget-edit.html`` template title and limit with angular ``limitTo`` filter in ``widget-title.html`` template who returns a string containing only a specified number of characters (in our case 20) and create condition that if the string is longer to shows only 20 characters. With this we will not have any problems with title length in both directions if we want to send or show title with more characters on the view.

And for task ``AFDP-647: Change layout editor`` I made changes in the same  ``angular-dashboard-framework-tpls.js`` file. In ``dashboard-edit.html`` template I added ``<image>`` tag with source code of images that are already added in ``assets/img/dashboard/``, that will replace the radio buttons with images when we want to click to shange the view of the widgets. And made changes in ``angular-dashboard-framework.css`` file to hide the radio buttons, make input not-clickable, remove input from document flow, image style before and after is clicked.
``INFO: the images are in list form, each other below not to right next them. That change it need to make some CSS developer, because I cannot solve that problem``.

This need to be done next: 
  1. Merged in to the develop branch, 
  2. Than to the master
  3. Create the tag from the master
      * git tag "v0.12.1"
  4. Push the tag 
      * git push --tag
  5. Registration of the bower package command to tell it to pick up the changes:
      * bower register angular-dashboard-framework-armedia git://github.com/Armedia/angular-dashboard-framework.git

@david-oc-miller  Should I create the tag and register the package from master after merging or you going to make it?

This merge requests are connected also with this one where I change the path of the ``all.js`` and ``bower.json`` package ``("angular-dashboard-framework-armedia")`` with our tag that need to create ``( "v0.12.1" )`` :
https://gitlab.armedia.com/arkcase/ACM3/merge_requests/784,
https://gitlab.armedia.com/arkcase/ACM3/merge_requests/830

### CODE REVIEW

**Comment by david-oc-miller** [comment]
@AngjelSpasovski Registration of the bower package only has to be done once, or should it be done at every build?

**Comment by david-oc-miller** [comment]
@marjan4jc please review Angjel's changes from the base framework.

**Comment by AngjelSpasovski** [comment]
@david-oc-miller  registration of the bower package only has to be done once and our library is ready to be used.

**Comment by marjan4jc** [comment]
👍 looks ok.

**Comment by david-oc-miller** [comment]
@AngjelSpasovski I have merged your change into develop, then into master... Can you apply the tag and register the package?  After that I will accept your merge requests in gitlab.

**Comment by AngjelSpasovski** [comment]
@david-oc-miller I apply the tag and register the package with older version because the new one need some dependency of bootstrap new version. And have some small changes in the ``angular-dashboard-framework.js`` file. I remove the referenced variable ``title`` and replace with ``editScope.definition.title``.

**Pull request merged**
